logging:
  level: INFO
  loggers:
    org.lelik: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
    - type: h2 #http2 protocol connection
      port: 8085
      keyStorePath: dropwizard-react-server/keystore # required
      keyStorePassword: 12345678
